# Generated by Django 3.2.9 on 2021-12-19 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20211217_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_counter',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 3, 43, 14, 151403)),
        ),
    ]
