# Generated by Django 3.2.9 on 2021-12-27 20:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='people_who_liked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_who_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 22, 52, 28, 710160)),
        ),
    ]
